import { Analytics } from '@vercel/analytics/react';
import Header from '@components/site/Header'
import '@styles/globals.css'
import { Inter } from 'next/font/google'
import Head from '@site/head'
import { draftMode } from 'next/headers';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
	const preview = draftMode().isEnabled ? { token: process.env.SANITY_API_READ_TOKEN } : undefined

  return (
		<html lang="en">
			<Head />
			<body className={inter.className}>
				<div id="modal-root"></div>
				<Header title={'title'} description={['description']} />
				{preview ? (
					<main className='[--total-header-height:calc(var(--header-height)+var(--preview-header-height))] mt-[--total-header-height]'>
						{children}
					</main>
				) : (
					<main className='[--total-header-height:var(--header-height)] mt-[--total-header-height]'>
						{children}
					</main>
				)}
				<Analytics />
			</body>
		</html>
  )
}