import { Analytics } from '@vercel/analytics/react';
import Header from '@components/site/Header'
import '@styles/globals.css'
import { Inter } from 'next/font/google'
import Head from '@site/head'
import { draftMode } from 'next/headers';
import { getClient } from '@/lib/sanity.client';
import { settingsQuery, siteSettings } from '@/lib/sanity.queries';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
	const preview = draftMode().isEnabled ? { token: process.env.SANITY_API_READ_TOKEN } : undefined
	const client = getClient(preview)
	const settings: siteSettings = await client.fetch(settingsQuery)

  return (
		<html lang="en" className="dark">
			<Head settings={settings}/>
			<body className={inter.className}>
				<div id="modal-root"></div>
				<Header preview={preview} settings={settings} />
				{preview ? (
					<main className='[--total-header-height:calc(var(--header-height)+var(--preview-header-height))] mt-[--total-header-height]'>
						{children}
					</main>
				) : (
					<main className='[--total-header-height:var(--header-height)] mt-[--total-header-height]'>
						{children}
					</main>
				)}
				<Analytics />
			</body>
		</html>
  )
}