import Header from '@components/site/Header'
import '@styles/globals.css'
import { Inter } from 'next/font/google'
import Head from '@site/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"> 
			<Head />
      <body className={inter.className}>
				<div id="modal-root"></div>
				<main>
					<Header title={'title'} description={['description']} />
					{children}
				</main>
			</body>
    </html>
  )
}
