query user {
  viewer {
		url,
    login,
    name,
    bio,
		email,
    pinnedItems(first:6) {
			nodes {
				... on Repository {
					...repo
				}
			}
    },
    socialAccounts(first:3) {
			nodes {
				provider,
				url
			}
    },
  }
}